config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :cursos
  resources :alunos
  resources :disciplinas

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    has_many :aluno_disciplinas # 1 pra n, cada aluno tem varias ocorrencias de "aluno_disciplinas"
    has_many :disciplinas, through: :aluno_disciplinas # n pra n, cada disciplina tem varias ocorrencias de "aluno_disciplinas" por meio da tabela "aluno_disciplinas"
end

app/models/aluno_disciplina.rb
class AlunoDisciplina < ApplicationRecord
    belongs_to :aluno
    belongs_to :disciplina
  # so olhar os ids que tem na relaçao que ajuda a definir o que precisa ter aqui
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/curso.rb
class Curso < ApplicationRecord
    has_many :disciplinas
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    belongs_to :curso # n pra 1
    has_many :aluno_disciplinas # indica que disciplina tem varios registros da relaçao "aluno_disciplinas"
    has_many :alunos, through: :aluno_disciplinas # alem disso, disciplina tem varios alunos, por meio da relacao "aluno_disciplinas"
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
    def index
        @alunos = Aluno.all
    end

    def show
        @aluno = Aluno.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
    def index
        @cursos = Curso.all
    end

    def show # pra ver todos os alunos desse curso
        @curso = Curso.find(params[:id])
    end
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
    def index
        @disciplinas = Disciplina.all
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/index.html.erb
<% content_for :title, "Alunos" %>

<h1>Alunos</h1>
<h3>Contagem total de alunos: <%=@alunos.count%></h3>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>
<div>
  <table border="1" cellpadding="10">
  <thead>
    <tr>
      <th>ID Aluno</th>
      <th>Matricula</th>
      <th>CR</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.id %></td>
        <td><%= aluno.matricula %></td>
        <td><%= aluno.cr %></td>
        <td><%= link_to "Mostrar mais", aluno %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div></br>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>

app/views/alunos/show.html.erb
  <h1> Aluno </h1>
  <div>
  <%= link_to "Voltar pra alunos", alunos_path %>
  </div>
  <p>
    <strong>Matricula:</strong>
    <%= @aluno.matricula %>
  </p>

  <p>
    <strong>CR:</strong>
    <%= @aluno.cr %>
  </p>

  <h2> Disciplinas cursadas: </h2>
  <table border="1" cellpadding="10">
  <thead>
    <tr>
      <th>Disciplina ID</th>
      <th>Código da Disciplina</th>
      <th>Carga Horaria</th>
      <th>Nota</th>
      <th>Ano Semestre</th>
      <th>Curso ID</th>
    </tr>
  </thead>
  <tbody>
  <tbody>
    <% @aluno.aluno_disciplinas.order(:ano_semestre).each do |aluno_disciplina| %>
      <tr>
        <td><%= aluno_disciplina.disciplina_id %></td>
        <td><%= aluno_disciplina.disciplina.codigo_disciplina %></td>
        <td><%= aluno_disciplina.disciplina.carga_horaria %></td>
        <td><%= aluno_disciplina.nota_aluno %></td>
        <td><%= aluno_disciplina.ano_semestre %></td>
        <td><%= aluno_disciplina.disciplina.curso_id %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
</br>
<div>
  <%= link_to "Voltar pra alunos", alunos_path %>
</div>

app/views/cursos/index.html.erb
<% content_for :title, "Cursos" %>

<h1>Cursos</h1>
<h3>Contagem total de cursos: <%=@cursos.count%></h3>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>
<div>
  <table border="1" cellpadding="10">
  <thead>
    <tr>
      <th>Curso ID</th>
      <th>Código Curso</th>
      <th>Media CR</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.id %></td>
        <td><%= curso.codigo_curso %></td>
        <td><%= curso.media_cr %></td>
        <td><%= link_to "Mostrar mais", curso %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div></br>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>

app/views/cursos/show.html.erb
<h1> Curso </h1>
<div>
<%= link_to "Voltar para cursos", cursos_path %>
</div>
<p>
  <strong>Curso ID:</strong>
  <%= @curso.id %>
</p>
<p>
  <strong>Código do Curso:</strong>
  <%= @curso.codigo_curso %>
</p>
<p>
  <strong>Média CR:</strong>
  <%= @curso.media_cr %>
</p>

<h2> Disciplinas desse curso: </h2>
<table border="1" cellpadding="10">
<thead>
  <tr>
    <th>Disciplina ID</th>
    <th>Código da disciplina</th>
  </tr>
</thead>
<tbody>
<tbody>
  <% @curso.disciplinas.each do |disciplina| %>
    <tr>
      <td><%= disciplina.id %></td>
      <td><%= disciplina.codigo_disciplina %></td>
    </tr>
  <% end %>
</tbody>
</table>
</div>
</br>
<div>
<%= link_to "Voltar para cursos", cursos_path %>
</div>

app/views/disciplinas/index.html.erb
<% content_for :title, "Disciplinas" %>

<h1>Disciplinas</h1>
<h3>Contagem total de disciplinas: <%=@disciplinas.count%></h3>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>
<div>
  <table border="1" cellpadding="10">
  <thead>
    <tr>
      <th>ID Disciplina</th>
      <th>Código da Disciplina</th>
      <th>CH</th>
    </tr>
  </thead>
  <tbody>
  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.id %></td>
        <td><%= disciplina.codigo_disciplina %></td>
        <td><%= disciplina.carga_horaria %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div></br>
<div>
  <%= link_to "Voltar para home", root_path %>
</div></br>

app/views/home/index.html.erb
<% content_for :title, "Home" %>

<h1>Home</h1>
<hr>
</br>
<div>
  <%= link_to "Listar alunos", alunos_path %>
</div>

<div>
  <%= link_to "Listar cursos", cursos_path %>
</div>

<div>
  <%= link_to "Listar disciplinas", disciplinas_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Calculo Cr" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>